name: Invoke Prepare Release

on:
  repository_dispatch:
    types: [invoke-release]

jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Perform the task
        run: echo "Triggered by Repo B workflow completion!"